name: test and lint the project
on: [push, pull_request]

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
          cache-dependency-path: go.sum

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
          cache-dependency-path: go.sum

      - name: test
        run: go test -v -json ./... > TestResults.json

      - name: Upload Go test results
        uses: actions/upload-artifact@v3
        with:
          name: TestResults
          path: TestResults.json
